import { Project } from "@/types";

export const PROJECTS: Project[] = [
  {
    id: "diehard-escape",
    title: "Diehard Escape",
    tagline: "Platform Web Interaktif & Sistem Tiket Online Arena Uji Nyali Bogor",
    category: "WEB",
    categoryLabel: "WEB APPLICATION // TICKETING & ENTERTAINMENT",
    year: "2026",
    overview:
      "Platform web reservasi tiket dan etalase wahana teater horor & aksi interaktif berdurasi 30 menit di Taman Topi Square Bogor. Menghadirkan sistem katalog film wahana, registrasi pengunjung, filter kategori atraksi, regulasi keselamatan medis, serta integrasi layanan konsultasi instan.",
    challenges: [
      "Mendesain antarmuka bertema horor modern yang imersif dan responsif dengan performa loading instan.",
      "Mengelola alur pemesanan tiket dan registrasi dengan validasi kuota kelompok pengunjung (4–6 orang per tim).",
      "Menyajikan panduan medis dan mitigasi risiko keselamatan pengunjung secara transparan dan mudah diakses.",
    ],
    keyFeatures: [
      "Katalog film wahana teater horor dengan live search dan preview poster interaktif.",
      "Alur reservasi tiket online dan integrasi direct customer service WhatsApp.",
      "Filter kategori film uji nyali dan ringkasan jadwal sesi pertunjukan.",
      "Panduan keselamatan & peringatan medis adaptif untuk pengunjung.",
    ],
    technologies: [
      "Next.js",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Framer Motion",
      "Lucide Icons",
      "RESTful API",
    ],
    architecture: {
      client: "Next.js App Router dengan SSR, dynamic routes, dan komponen interaktif modern",
      server: "Next.js Server Endpoints & Node.js REST API",
      database: "Relational Database / Cloud Datastore dengan query indexing efisien",
      deployment: "Production Edge Cloud Platform, SSL HTTPS, dan Global CDN",
    },
    metrics: [
      { label: "Performa Web", value: "95+ Score" },
      { label: "Waktu Reservasi", value: "< 1 Menit" },
      { label: "Responsivitas", value: "Fluid Mobile/Desktop" },
    ],
    liveUrl: "https://diehardescape.com",
    isFeatured: true,
  },
  {
    id: "smartdigi-superapp",
    title: "Proyek Smartdigi",
    tagline: "Super App Antarmuka Pelayanan Publik Pemerintah Kabupaten Subang",
    category: "MOBILE",
    categoryLabel: "MOBILE APPLICATION // GOVTECH",
    year: "2025",
    overview:
      "Aplikasi mobile multi-layanan publik terpadu yang dirancang untuk menghubungkan warga Kabupaten Subang dengan berbagai dinas pemerintah daerah. Menghadirkan portal pengaduan aspirasi warga, informasi layanan perizinan, pemantauan status berkas, dan berita resmi daerah dalam satu antarmuka modern yang ramah pengguna.",
    challenges: [
      "Mengintegrasikan beragam endpoint API dinas dengan format respon yang bervariasi menjadi struktur data seragam di aplikasi.",
      "Memastikan navigasi aplikasi tetap lancar pada berbagai spesifikasi perangkat Android dari kelas entry-level hingga flagship.",
      "Menyediakan sistem caching offline-first untuk modul informasi publik agar tetap dapat diakses saat koneksi internet lemah.",
    ],
    keyFeatures: [
      "Modul Layanan Aspirasi Warga dengan upload lampiran foto bukti & tracking tiket laporan.",
      "Katalog informasi izin usaha dan kependudukan dengan panduan interaktif.",
      "Integrasi push notification darurat daerah dan pengumuman dinas resmi.",
      "Desain antarmuka modular sesuai identitas visual daerah dan standar aksesibilitas ramah lansia.",
    ],
    technologies: [
      "Flutter",
      "Dart",
      "Provider / BLoC",
      "REST API",
      "Dio HTTP Client",
      "SQLite / Hive Storage",
      "Google Maps API",
    ],
    architecture: {
      client: "Flutter Cross-Platform Mobile Application (Android & iOS)",
      server: "Microservices Government Backend API Gateway",
      database: "Local Hive/SQLite cache untuk mode offline & sinkronisasi data",
      deployment: "Android APK & Play Console Testing Distribution",
    },
    metrics: [
      { label: "Cakupan Layanan", value: "5+ Dinas Terintegrasi" },
      { label: "Arsitektur", value: "Clean Architecture Flutter" },
      { label: "Performa UI", value: "60 FPS Smooth Flow" },
    ],
    isFeatured: true,
  },
  {
    id: "ym-wedding-studio",
    title: "YM Wedding Studio",
    tagline: "Platform Web Editorial & Sistem Kurasi Paket Rias Pengantin / WO Subang",
    category: "WEB",
    categoryLabel: "WEB APPLICATION // EDITORIAL & SERVICES",
    year: "2026",
    overview:
      "Platform web editorial kurasi paket pernikahan, katalog rias pengantin premium (MUA), dan layanan wedding organizer one-stop service untuk wilayah Subang dan sekitarnya. Menyajikan perincian paket bertingkat (Melati, Teratai, Tulip), galeri portofolio visual, testimoni klien, dan konsultasi interaktif.",
    challenges: [
      "Merancang arsitektur visual editorial elegan dengan hierarki tipografi tinggi yang bebas dari layout template kaku.",
      "Mengelola struktur data perincian paket yang kompleks (tenda, dekorasi, busana, prasmanan) agar mudah dikomparasi calon pengantin.",
      "Mengoptimalkan dynamic image loading untuk galeri foto pernikahan beresolusi tinggi dengan kompresi modern.",
    ],
    keyFeatures: [
      "Katalog paket pernikahan berjenjang (Paket Melati, Teratai, Tulip) lengkap dengan rincian fasilitas tenda & katering.",
      "Integrasi one-click consultation ke WhatsApp dengan template pesan terformat otomatis sesuai paket.",
      "Galeri portofolio visual interaktif & jurnal pengantin dengan navigasi responsif.",
      "Section ulasan & testimoni klien terverifikasi dengan tautan media sosial resmi (Instagram & TikTok).",
    ],
    technologies: [
      "Next.js",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Responsive Design",
      "SEO Structured Data",
      "WhatsApp Direct",
    ],
    architecture: {
      client: "Next.js App dengan layout editorial magazine & rich typography",
      server: "Server-Side Rendering (SSR) & Static Site Generation (SSG) untuk SEO lokal Subang",
      database: "Headless Storage / Relational Database untuk data katalog paket & galeri",
      deployment: "Custom Domain HTTPS dengan Global Edge Network & Asset Optimization",
    },
    metrics: [
      { label: "SEO Indexing", value: "100% Structured Data" },
      { label: "Format Gambar", value: "Modern WebP/AVIF" },
      { label: "Aksesibilitas", value: "100/100 Web Standards" },
    ],
    liveUrl: "https://ymwedding.id",
    isFeatured: true,
  },
];
